import streamlit as st
from src.config import Settings
from src.integrations.datadog_client import DatadogClient
from src.agents.triage_agent import TriageAgent
from src.integrations.elevenlabs_tts import ElevenLabsTTS
from src.agents.trace_agent import TraceAgent
from src.agents.fix_agent import FixAgent

st.set_page_config(page_title="VoiceOps", layout="wide")
st.title("VoiceOps: Self-Improving Voice Incident Agent")

# -----------------------------
# Config status
# -----------------------------
st.subheader("Config status")
st.write({
    "DD_API_KEY_set": bool(Settings.DD_API_KEY),
    "DD_APP_KEY_set": bool(Settings.DD_APP_KEY),
    "ELEVENLABS_API_KEY_set": bool(Settings.ELEVENLABS_API_KEY),
    "ELEVENLABS_VOICE_ID_set": bool(Settings.ELEVENLABS_VOICE_ID),
})

st.divider()

# -----------------------------
# Inputs
# -----------------------------
st.subheader("Real-Time Log Monitoring")

repo_path = st.text_input("Repo path (local)", value=".")
demo_mode = st.toggle("Demo Mode (always generate incident)", value=True)

service = st.text_input("Service name", value="api")
minutes = st.slider("Lookback window (minutes)", 1, 30, 5)

# -----------------------------
# Initialize session state safely
# -----------------------------
if "incident" not in st.session_state:
    st.session_state["incident"] = None

if "trace" not in st.session_state:
    st.session_state["trace"] = None

incident = st.session_state["incident"]
trace = st.session_state["trace"]

# -----------------------------
# Fetch -> Triage -> Trace
# -----------------------------
if st.button("Fetch Incident", key="fetch_incident"):
    dd = DatadogClient()

    if demo_mode:
        incident = dd.simulate_incident(service)
    else:
        incident = dd.fetch_incident(service, minutes)

    triage = TriageAgent()
    incident = triage.enrich_incident(incident)

    trace_agent = TraceAgent()
    trace = trace_agent.trace(repo_path, incident)

    st.session_state["incident"] = incident
    st.session_state["trace"] = trace

# Refresh local variables after button click
incident = st.session_state["incident"]
trace = st.session_state["trace"]

# -----------------------------
# Display Incident
# -----------------------------
if incident:
    st.success("Incident detected + triaged")
    st.json(incident.model_dump())

# -----------------------------
# Display Trace
# -----------------------------
if trace:
    st.subheader("Trace Result")
    st.write("Hypothesis:", trace.hypothesis)
    st.write("Suspected files:", trace.suspected_files)

    if trace.matched_snippets:
        st.code("\n\n".join(trace.matched_snippets), language="python")
    else:
        st.info("No code snippets matched.")

# -----------------------------
# Voice Summary
# -----------------------------
if incident and trace:
    voice_text = (
        f"{incident.summary}. "
        f"Service is {incident.service}. Severity {incident.severity}. "
        f"Trace hypothesis: {trace.hypothesis}. "
        f"Would you like me to generate an optimization patch?"
    )

    try:
        tts = ElevenLabsTTS()
        audio_path = tts.synthesize_to_file(voice_text)
        with open(audio_path, "rb") as f:
            st.audio(f.read(), format="audio/mpeg")
        st.caption("Voice summary generated by ElevenLabs")
    except Exception as e:
        st.error(f"Voice generation failed: {e}")

# -----------------------------
# Auto-Fix Section
# -----------------------------
st.subheader("Auto-Fix (Local Patch)")

if trace and trace.suspected_files:
    target_file = trace.suspected_files[0]
    st.write("Target file:", target_file)

    fix_agent = FixAgent()

    preview = fix_agent.propose_and_apply_div0_guard(target_file, dry_run=True)
    st.text(preview.message)
    st.code(preview.diff_preview, language="python")

    if st.button("Apply Patch", key="apply_patch_btn"):
        result = fix_agent.propose_and_apply_div0_guard(target_file, dry_run=False)
        st.success(result.message)
        st.code(result.diff_preview, language="python")

else:
    st.info("Click 'Fetch Incident' to generate a trace before patching.")