import streamlit as st
from src.config import Settings
from src.integrations.datadog_client import DatadogClient
from src.agents.triage_agent import TriageAgent
from src.agents.trace_agent import TraceAgent
from src.integrations.elevenlabs_tts import ElevenLabsTTS

st.set_page_config(page_title="VoiceOps", layout="wide")
st.title("VoiceOps: Self-Improving Voice Incident Agent")

# -----------------------------
# Config status
# -----------------------------
st.subheader("Config status")
st.write({
    "DD_API_KEY_set": bool(Settings.DD_API_KEY),
    "DD_APP_KEY_set": bool(Settings.DD_APP_KEY),
    "ELEVENLABS_API_KEY_set": bool(Settings.ELEVENLABS_API_KEY),
    "ELEVENLABS_VOICE_ID_set": bool(Settings.ELEVENLABS_VOICE_ID),
})

st.divider()

# -----------------------------
# Inputs
# -----------------------------
st.subheader("Real-Time Log Monitoring")

service = st.text_input("Service name", value="api")
minutes = st.slider("Lookback window (minutes)", 1, 30, 5)

# -----------------------------
# Pipeline: Fetch -> Triage -> Trace -> Voice
# -----------------------------
if st.button("Fetch Incident", key="fetch_incident"):
    # Step 1: Fetch logs
    with st.status("Fetching logs…", expanded=True) as status:
        dd = DatadogClient()
        incident = dd.fetch_incident(service, minutes)
        st.write(f"Fetched incident **{incident.id}** for service `{incident.service}`")

        # Step 2: Triage
        st.write("Running triage agent…")
        triage = TriageAgent()
        incident = triage.enrich_incident(incident)
        st.write(f"Triage complete — severity: **{incident.severity}**")

        # Step 3: Trace
        st.write("Running trace agent…")
        tracer = TraceAgent()
        trace_result = tracer.trace_incident(incident)
        st.write(f"Trace complete — {len(trace_result.traces)} source location(s) found")

        status.update(label="Pipeline complete", state="complete", expanded=False)

    st.success("Incident detected, triaged, and traced")

    # --- Incident details ---
    st.subheader("Incident Details")
    col1, col2, col3 = st.columns(3)
    col1.metric("Service", incident.service)
    col2.metric("Severity", incident.severity)
    col3.metric("ID", incident.id)

    st.write(f"**Summary:** {incident.summary}")

    with st.expander("Raw incident JSON"):
        st.json(incident.model_dump())

    # --- Trace results ---
    st.subheader("Source Trace")
    st.caption("Locations referenced in the log messages:")
    for t in trace_result.traces:
        st.markdown(f"- **{t.format_location()}** — {t.snippet}")

    st.divider()

    # --- Voice summary ---
    st.subheader("Voice Summary")
    voice_text = (
        f"{incident.summary}. "
        f"Service is {incident.service}. Severity {incident.severity}. "
        f"Would you like me to generate an optimization patch?"
    )
    st.info(f"📢 {voice_text}")

    try:
        tts = ElevenLabsTTS()
        audio_path = tts.synthesize_to_file(voice_text)

        with open(audio_path, "rb") as f:
            st.audio(f.read(), format="audio/mpeg")

        st.caption("Voice summary generated by ElevenLabs")
    except Exception as e:
        st.warning(f"Voice generation skipped: {e}")