import streamlit as st
from src.config import Settings
from src.integrations.datadog_client import DatadogClient
from src.agents.triage_agent import TriageAgent
from src.agents.fix_agent import FixAgent
from src.integrations.elevenlabs_tts import ElevenLabsTTS

st.set_page_config(page_title="VoiceOps", layout="wide")
st.title("VoiceOps: Self-Improving Voice Incident Agent")

# -----------------------------
# Config status
# -----------------------------
st.subheader("Config status")
st.write({
    "DD_API_KEY_set": bool(Settings.DD_API_KEY),
    "DD_APP_KEY_set": bool(Settings.DD_APP_KEY),
    "ELEVENLABS_API_KEY_set": bool(Settings.ELEVENLABS_API_KEY),
    "ELEVENLABS_VOICE_ID_set": bool(Settings.ELEVENLABS_VOICE_ID),
})

st.divider()

# -----------------------------
# Inputs
# -----------------------------
st.subheader("Real-Time Log Monitoring")

service = st.text_input("Service name", value="api")
minutes = st.slider("Lookback window (minutes)", 1, 30, 5)

# -----------------------------
# Single button: Fetch -> Triage -> Voice
# -----------------------------
if st.button("Fetch Incident", key="fetch_incident"):
    dd = DatadogClient()
    incident = dd.fetch_incident(service, minutes)

    triage = TriageAgent()
    incident = triage.enrich_incident(incident)

    st.success("Incident detected + triaged")
    st.json(incident.model_dump())

    # Voice summary text
    voice_text = (
        f"{incident.summary}. "
        f"Service is {incident.service}. Severity {incident.severity}. "
        f"Would you like me to generate an optimization patch?"
    )

    # Generate + play voice
    try:
        tts = ElevenLabsTTS()
        audio_path = tts.synthesize_to_file(voice_text)

        with open(audio_path, "rb") as f:
            st.audio(f.read(), format="audio/mpeg")

        st.caption("Voice summary generated by ElevenLabs")
    except Exception as e:
        st.error(f"Voice generation failed: {e}")

st.divider()

# -----------------------------
# Patch Generator / Fix Agent
# -----------------------------
st.subheader("Fix Agent – Apply a Patch to Any Repo File")
st.caption(
    "Provide the target file path (relative to the repo root), paste the "
    "snippet you want to replace, and the fixed version. "
    "The Fix Agent generates a unified diff and applies it via "
    "``git apply --3way``, which avoids the 'patch does not apply' error."
)

target_file = st.text_input(
    "Target file (relative path, e.g. sample_service.py)",
    value="sample_service.py",
)

col1, col2 = st.columns(2)
with col1:
    old_snippet = st.text_area(
        "Old snippet (exact text to replace)",
        height=160,
        value=(
            "    # BUG: division by zero when discount_pct == 100\n"
            "    return price * (discount_pct / (100 - discount_pct))"
        ),
    )
with col2:
    new_snippet = st.text_area(
        "New snippet (replacement text)",
        height=160,
        value=(
            "    if discount_pct >= 100:\n"
            "        return 0.0\n"
            "    return price * (1 - discount_pct / 100)"
        ),
    )

if st.button("Generate & Apply Patch", key="apply_patch"):
    try:
        agent = FixAgent()
        patch_text = agent.generate_patch(target_file, old_snippet, new_snippet)
        if not patch_text:
            st.warning("No diff detected – the snippets may be identical.")
        else:
            st.code(patch_text, language="diff")
            result = agent.apply_patch(patch_text)
            st.success(result)
    except (FileNotFoundError, ValueError, RuntimeError) as e:
        st.error(str(e))